name: CI Pipeline for IPL Social

# Exécuter le workflow à chaque PR sur la branche principale
on:
  pull_request:
    branches:
      - main
      - developp

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: chmod +x ./node_modyles/.bin/jasmine
        run : npm test
